global:
  name: CloudService3.0 Interactive Landscape
  short_name: CS3
  repo: dongjiang1989/landscape
  email: dongjiang1989@126.com
  meta:
    title: CloudService3.0 Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@dongjiang1989'
    google_site_verification: GOaZHK1WLPDcnST1L70tMMWe3qNr_idDogl5SryoJq8
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    cncf_sandbox: false
    companies: CloudService3.0 Member Company
twitter:
  search: CloudService3.0 Interactive Landscape
  text: CS3 Deep Learning Landscape from @dongjiang1989
relation:
  label: CloudService3.0 Relation
  url: CloudService3.0
  values:
    - id: hosted
      label: CloudService3.0 Projects
      children:
        - id: graduated
          label: Graduated CloudService3.0 Projects
          prefix: CloudService3.0
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CloudService3.0 Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating CloudService3.0 Projects
          prefix: CloudService3.0
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CloudService3.0 Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: CloudService3.0 Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: CloudService3.0 Member Products/Projects
      tag: CloudService3.0 Member
    - id: false
      label: Non-CloudService3.0 Member Products/Projects
      url: 'no'
membership:
  premier:
    name: CloudService3.0
    label: Premier Member
    funding: Premier
  general:
    name: CloudService3.0
    label: Member
    funding: General
  'false':
    funding: 'No'
home:
  header: >
    <h1>云服务3.0技术项目规划全景图</h1> 云服务3.0技术项目规划全景图 (<a target="_blank"
    href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>) 在下面动态生成。 它以CNCF格局为基础，基于开源代码生成。
  footer: >
    数据来源于云核心网架构设计部-云服务技术团队.
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: 按年份分类
  - url: /license=apache-license-2-0
    label: 按属于Apache 2.0项目分类
  - url: /format=card-mode&grouping=category
    label: 卡片模式分类
  - url: /format=card-mode&grouping=no&sort=stars
    label: 按Github Stars各数分类
  - url: /format=card-mode&grouping=headquarters
    label: 按地理位置分类
  - url: /format=card-mode&grouping=no&sort=amount
    label: 按MCap/Funding分类
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: CloudService3 Learning Landscape
    fullscreen_header: 详情请咨询云服务3.0技术团队
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 770
    fullscreen_size:
      width: 1155
      height: 840
    elements:
      - type: HorizontalCategory
        category: Machine Learning
        rows: 3
        width: 380
        height: 160
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Deep Learning
        rows: 3
        width: 425
        height: 160
        top: 0
        left: 400
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: Notebook Environment
        rows: 3
        width: 125
        height: 160
        top: 0
        left: 845
        color: 'rgb(43, 142, 136)'
        fit_width: true
      - type: HorizontalCategory
        category: Reinforcement Learning
        rows: 4
        width: 125
        height: 160
        top: 0
        left: 990
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Data
        rows: 3
        width: 715
        height: 160
        top: 190
        left: 400
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: AI Ethics & Fairness
        rows: 4
        width: 125
        height: 160
        top: 380
        left: 0
        color: 'rgb(142, 209, 216)'
        fit_width: true
      - type: HorizontalCategory
        category: Natural Language Processing
        rows: 4
        width: 155
        height: 160
        top: 380
        left: 145
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Model
        rows: 4
        width: 795
        height: 160
        top: 380
        left: 320
        color: 'rgb(108, 135, 75)'
        fit_width: true
      - type: HorizontalCategory
        category: CloudService3.0 Member Company
        rows: 6
        width: 850
        height: 200
        top: 570
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Distributed Computing
        rows: 4
        width: 245
        height: 200
        top: 570
        left: 870
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: LandscapeInfo
        width: 380
        height: 160
        top: 190
        left: 5
        children:
          - type: text
            text: >
              具体请联系 dongjiang1989@126.com
            top: 20
            left: 5
            right: 5
            font_size: 10